<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Product;
use Carbon\Carbon;
use Illuminate\Support\Str;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $products = [
            [
                'sku' => 'BIO-Q4154',
                'name' => 'Biovance',
                'description' => 'Decellularized, dehydrated human amniotic membrane that preserves the natural extracellular matrix components. Promotes cellular migration and supports wound closure.',
                'manufacturer' => 'CELULARITY',
                'category' => 'SkinSubstitute',
                'q_code' => '4154',
                'price_per_sq_cm' => 550.64,
                'available_sizes' => [2, 4, 6, 8, 10.5, 16, 25, 36],
                'graph_type' => 'Amniotic Membrane',
                'commission_rate' => 5.0,
            ],
            [
                'sku' => 'IMP-Q4262',
                'name' => 'Impax Dual Layer Membrane',
                'description' => 'Advanced dual-layer membrane designed for complex wound management.',
                'manufacturer' => 'LEGACY MEDICAL CONSULTANTS',
                'category' => 'SkinSubstitute',
                'q_code' => '4262',
                'price_per_sq_cm' => 169.86,
                'available_sizes' => [4, 6, 16, 24, 32],
                'graph_type' => 'Dual Layer',
                'commission_rate' => 6.0,
            ],
            [
                'sku' => 'HEL-Q4164',
                'name' => 'Helicoll',
                'description' => 'Collagen-based wound matrix that provides structural support for tissue regeneration.',
                'manufacturer' => 'ENCOLL CORP',
                'category' => 'SkinSubstitute',
                'q_code' => '4164',
                'price_per_sq_cm' => 322.15,
                'available_sizes' => [1.27, 5.07, 8, 12, 16, 25, 50],
                'graph_type' => 'Collagen Matrix',
                'commission_rate' => 7.5,
            ],
            [
                'sku' => 'ZEN-Q4253',
                'name' => 'Zenith',
                'description' => 'Cost-effective wound care solution for routine wound management.',
                'manufacturer' => 'LEGACY MEDICAL CONSULTANTS',
                'category' => 'SkinSubstitute',
                'q_code' => '4253',
                'price_per_sq_cm' => 71.49,
                'available_sizes' => [4, 6, 16, 24, 32],
                'graph_type' => 'Basic Matrix',
                'commission_rate' => 8.0,
            ],
            [
                'sku' => 'ORI-Q4276',
                'name' => 'Orion',
                'description' => 'Premium wound care matrix with enhanced healing properties.',
                'manufacturer' => 'LEGACY MEDICAL CONSULTANTS',
                'category' => 'SkinSubstitute',
                'q_code' => '4276',
                'price_per_sq_cm' => 464.34,
                'available_sizes' => [4, 6, 16, 24, 32],
                'graph_type' => 'Premium Matrix',
                'commission_rate' => 6.5,
            ],
            [
                'sku' => 'COM-Q4271',
                'name' => 'Complete FT',
                'description' => 'Advanced full-thickness skin substitute designed specifically for deeper wounds with exposed structures.',
                'manufacturer' => 'EXTREMITY CARE',
                'category' => 'SkinSubstitute',
                'q_code' => '4271',
                'price_per_sq_cm' => 1399.12,
                'available_sizes' => [3, 4, 6, 8, 16, 18, 24, 32],
                'graph_type' => 'Full Thickness',
                'commission_rate' => 4.0,
            ],
            [
                'sku' => 'BAR-Q4281',
                'name' => 'Barrera DL',
                'description' => 'Dual-layer barrier system for enhanced wound protection and healing.',
                'manufacturer' => 'EXTREMITY CARE',
                'category' => 'SkinSubstitute',
                'q_code' => '4281',
                'price_per_sq_cm' => 560.29,
                'available_sizes' => [3, 4, 6, 8, 16, 24, 32],
                'graph_type' => 'Dual Layer Barrier',
                'commission_rate' => 5.5,
            ],
            [
                'sku' => 'CAR-Q4236',
                'name' => 'carePatch Amniotic Membrane',
                'description' => 'Amniotic membrane patch for promoting cellular migration and wound healing.',
                'manufacturer' => 'EXTREMITY CARE',
                'category' => 'Biologic',
                'q_code' => '4236',
                'price_per_sq_cm' => 482.71,
                'available_sizes' => [1.13, 2, 4, 6, 8, 16, 24, 25, 32],
                'graph_type' => 'Amniotic Patch',
                'commission_rate' => 6.0,
            ],
            [
                'sku' => 'MEM-Q4205',
                'name' => 'Membrane Wrap',
                'description' => 'Versatile membrane wrap for various wound types and applications.',
                'manufacturer' => 'BLS SALES AND MARKETING LLC',
                'category' => 'Biologic',
                'q_code' => '4205',
                'price_per_sq_cm' => 1055.97,
                'available_sizes' => [1, 4, 6, 16, 24, 32, 48, 64, 100],
                'graph_type' => 'Membrane Wrap',
                'commission_rate' => 4.5,
            ],
            [
                'sku' => 'MEM-Q4290',
                'name' => 'Membrane Wrap - Hydro',
                'description' => 'Hydrated membrane wrap with enhanced healing properties.',
                'manufacturer' => 'BLS SALES AND MARKETING LLC',
                'category' => 'Biologic',
                'q_code' => '4290',
                'price_per_sq_cm' => 1841.00,
                'available_sizes' => [4, 6, 16, 24, 32, 100, 300, 480],
                'graph_type' => 'Hydrated Membrane',
                'commission_rate' => 3.5,
            ],
            [
                'sku' => 'NEO-Q4265',
                'name' => 'NeoStim TL',
                'description' => 'Triple-layer wound matrix for complex wound management.',
                'manufacturer' => 'DYNAMIC MEDICAL SERVICES, LLC',
                'category' => 'SkinSubstitute',
                'q_code' => '4265',
                'price_per_sq_cm' => 1750.26,
                'available_sizes' => [1, 2, 4, 6, 8, 16, 24, 32],
                'graph_type' => 'Triple Layer',
                'commission_rate' => 3.0,
            ],
            [
                'sku' => 'NEO-Q4267',
                'name' => 'NeoStim DL',
                'description' => 'Dual-layer wound matrix for enhanced healing outcomes.',
                'manufacturer' => 'DYNAMIC MEDICAL SERVICES, LLC',
                'category' => 'SkinSubstitute',
                'q_code' => '4267',
                'price_per_sq_cm' => 274.60,
                'available_sizes' => [1, 4, 6, 16, 24, 32],
                'graph_type' => 'Dual Layer',
                'commission_rate' => 7.0,
            ],
            [
                'sku' => 'NEO-Q4266',
                'name' => 'NeoStim SL',
                'description' => 'Single-layer wound matrix for routine wound care.',
                'manufacturer' => 'DYNAMIC MEDICAL SERVICES, LLC',
                'category' => 'SkinSubstitute',
                'q_code' => '4266',
                'price_per_sq_cm' => 989.67,
                'available_sizes' => [4, 6, 16, 24, 32],
                'graph_type' => 'Single Layer',
                'commission_rate' => 4.5,
            ],
            [
                'sku' => 'RES-Q4191',
                'name' => 'Restorigin',
                'description' => 'Regenerative biologic matrix for tissue restoration.',
                'manufacturer' => 'EXTREMITY CARE',
                'category' => 'Biologic',
                'q_code' => '4191',
                'price_per_sq_cm' => 940.15,
                'available_sizes' => [1, 2.25, 4, 6, 8, 16, 24, 25, 32],
                'graph_type' => 'Regenerative Matrix',
                'commission_rate' => 5.0,
            ],
            [
                'sku' => 'WOU-Q4217',
                'name' => 'WoundFix',
                'description' => 'Advanced wound repair matrix for accelerated healing.',
                'manufacturer' => 'HUMAN REGENERATIVE TECHNOLOGIES, LLC',
                'category' => 'Biologic',
                'q_code' => '4217',
                'price_per_sq_cm' => 273.51,
                'available_sizes' => [4, 8, 16, 32],
                'graph_type' => 'Repair Matrix',
                'commission_rate' => 8.0,
            ],
            [
                'sku' => 'COM-Q4302',
                'name' => 'Complete ACA',
                'description' => 'Advanced cellular allograft for complex wound management.',
                'manufacturer' => 'LEGACY MEDICAL CONSULTANTS',
                'category' => 'SkinSubstitute',
                'q_code' => '4302',
                'price_per_sq_cm' => 2008.70,
                'available_sizes' => [4, 6, 16, 24, 32],
                'graph_type' => 'Cellular Allograft',
                'commission_rate' => 2.5,
            ],
            [
                'sku' => 'PRO-Q4310',
                'name' => 'Procenta',
                'description' => 'Concentrated biologic solution for wound healing enhancement.',
                'manufacturer' => 'EXTREMITY CARE',
                'category' => 'Biologic',
                'q_code' => '4310',
                'price_per_sq_cm' => 2213.13,
                'available_sizes' => [1, 2, 3], // Units of 100mg
                'graph_type' => 'Concentrated Solution',
                'commission_rate' => 3.0,
            ],
            [
                'sku' => 'REV-Q4289',
                'name' => 'RevoShield +',
                'description' => 'Enhanced protective shield for wound management.',
                'manufacturer' => 'REVOGEN BIOLOGICS / MINDSIGHT MEDICAL',
                'category' => 'SkinSubstitute',
                'q_code' => '4289',
                'price_per_sq_cm' => 1602.22,
                'available_sizes' => [1, 4, 6, 8, 16, 24, 32],
                'graph_type' => 'Protective Shield',
                'commission_rate' => 3.5,
            ],
            [
                'sku' => 'AMN-Q4250',
                'name' => 'AmnioAMP-MP',
                'description' => 'Multi-purpose amniotic membrane for diverse wound applications.',
                'manufacturer' => 'STRATUS BIOSYSTEMS LLC',
                'category' => 'Biologic',
                'q_code' => '4250',
                'price_per_sq_cm' => 2863.13,
                'available_sizes' => [4, 6, 8, 16, 24, 32, 128, 180, 252],
                'graph_type' => 'Multi-Purpose Amniotic',
                'commission_rate' => 2.0,
            ],
            [
                'sku' => 'COM-Q4303',
                'name' => 'Complete AA',
                'description' => 'Advanced acellular allograft for tissue regeneration.',
                'manufacturer' => 'SAMARITAN BIOLOGICS, LLC',
                'category' => 'SkinSubstitute',
                'q_code' => '4303',
                'price_per_sq_cm' => 3397.40,
                'available_sizes' => [4, 8, 16, 32],
                'graph_type' => 'Acellular Allograft',
                'commission_rate' => 1.5,
            ],
            [
                'sku' => 'COM-Q4270',
                'name' => 'Complete SL',
                'description' => 'Single-layer complete wound coverage solution.',
                'manufacturer' => 'SAMARITAN BIOLOGICS, LLC',
                'category' => 'SkinSubstitute',
                'q_code' => '4270',
                'price_per_sq_cm' => 3370.80,
                'available_sizes' => [4, 8, 16, 32, 300],
                'graph_type' => 'Single Layer Complete',
                'commission_rate' => 1.5,
            ],
            [
                'sku' => 'XCE-Q4234',
                'name' => 'Xcellerate',
                'description' => 'Accelerated healing matrix for faster wound closure.',
                'manufacturer' => 'PRECISE BIOSCIENCE',
                'category' => 'SkinSubstitute',
                'q_code' => '4234',
                'price_per_sq_cm' => 247.91,
                'available_sizes' => [0.283, 0.64, 1.13, 4, 6, 8, 16, 28],
                'graph_type' => 'Accelerated Matrix',
                'commission_rate' => 8.5,
            ],
            [
                'sku' => 'EPI-Q4186',
                'name' => 'EpiFix',
                'description' => 'Dehydrated Human Amnion/Chorion Membrane (dHACM) containing over 300 regulatory proteins.',
                'manufacturer' => 'MIMEDX GROUP, INC.',
                'category' => 'Biologic',
                'q_code' => '4186',
                'price_per_sq_cm' => 158.34,
                'available_sizes' => [1.54, 2, 2.5, 4, 4.5, 6, 8, 9, 9.5, 10.1, 12, 15, 16, 16.2, 16.9, 24, 30, 49],
                'graph_type' => 'dHACM',
                'commission_rate' => 9.0,
            ],
            [
                'sku' => 'EPI-Q4187',
                'name' => 'EpiCord',
                'description' => 'Umbilical cord-derived matrix for wound healing enhancement.',
                'manufacturer' => 'MIMEDX GROUP, INC.',
                'category' => 'Biologic',
                'q_code' => '4187',
                'price_per_sq_cm' => 247.91,
                'available_sizes' => [2, 6, 15],
                'graph_type' => 'Umbilical Cord Matrix',
                'commission_rate' => 8.0,
            ],
            [
                'sku' => 'AMN-Q4239',
                'name' => 'Amnio-Maxx',
                'description' => 'Maximum strength amniotic membrane for challenging wounds.',
                'manufacturer' => 'ROYAL BIOLOGICS',
                'category' => 'Biologic',
                'q_code' => '4239',
                'price_per_sq_cm' => 2349.92,
                'available_sizes' => [4, 6, 8, 9, 16, 24, 32],
                'graph_type' => 'Maximum Strength Amniotic',
                'commission_rate' => 2.5,
            ]
        ];

        foreach ($products as $productData) {
            Product::create([
                'id' => (string) Str::uuid(),
                'sku' => $productData['sku'],
                'name' => $productData['name'],
                'description' => $productData['description'],
                'manufacturer' => $productData['manufacturer'],
                'category' => $productData['category'],
                'q_code' => $productData['q_code'],
                'price_per_sq_cm' => $productData['price_per_sq_cm'],
                'available_sizes' => $productData['available_sizes'],
                'graph_type' => $productData['graph_type'],
                'commission_rate' => $productData['commission_rate'],
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ]);
        }

        $this->command->info('Successfully seeded ' . count($products) . ' products.');
    }
}
