# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy PHP app to Azure Web App - msc-prod

on:
  push:
    branches:
      - uat-branch
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    env:
     AZURE_FHIR_BASE_URL: "https://medexchangefhir-fhirserver.fhir.azurehealthcareapis.com"
     AZURE_FHIR_URL: "https://medexchangefhir-fhirserver.fhir.azurehealthcareapis.com"
     AZURE_FHIR_CLIENT_ID: 032a9600-5750-495b-bb91-122a4faea0da
     AZURE_FHIR_CLIENT_SECRET: Gqb8Q~dldpP1hlU-SVT8w8Vo_8JpxMjAttHWRdgx
     AZURE_FHIR_TENANT_ID: 0cb4abeb-8281-4b8c-8de8-6a7f8c777f0a
     DOCUSEAL_API_BASE_URL: https://api.docuseal.com/v1
     DOCUSEAL_API_KEY: RDiw3DDJVmRqKVYMCeqXVqmZg1zg4WfvReWNnRAmrUD
     steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Check if composer.json exists
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: 'composer.json'

      - name: Run composer install if composer.json exists
        if: steps.check_files.outputs.files_exists == 'true'
        run: |
          rm -f bootstrap/cache/*.php
          composer validate --no-check-publish
          composer install --prefer-dist --no-progress
      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: php-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build


    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: php-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_642CAC2C5D714C05BABC3DD00E2D30D6 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_27574C25F73A4901B7EAC987626FF1BA }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_C55B987BA5254B76BC6D5909EFA576F4 }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'msc-prod'
          slot-name: 'uat'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_57CB6B14457348859FF71C079CAFDCCD }}
